name: 'Docker Semver'
author: 'Mirza Merdovic'
branding:
  icon: 'anchor'
  color: 'black'
description: 'Uses the SemVer for image tags'
inputs:
  name:
    description: 'The name of the image you would like to push'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  registry:
    description: 'Use registry for pushing to a custom registry'
    required: false
  dockerfile:
    description: 'Use dockerfile when you would like to explicitly build a Dockerfile'
    required: false
  workdir:
    description: 'Use workdir when you would like to change the directory for building'
    required: false
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
  semver:
    description: 'User semver if you want to push with semvar tags'
    required: false
outputs:
  tag:
    description: 'Is the tag, which was pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
