name: Integration Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: MirzaMerdovic/Publish-Docker-Github-Action@master
      with:
        name: mirzamerdovic/publish-docker-github-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        semver: 1.3.2
